### ISSUE TITLE
1.1.0 app error and not working correctly

### ISSUE THREAD

**Issue by neonturbo** [richardpowellus/HBBWASpaManager#1]
I posted something similar on Hubitat forum too. This happened on 1.1.0 and not the previous version.

The new auto detect worked fine. So that is good.

Unfortunately, there is something severely wrong with the app. It spams my hub multiple times per second with an error. I cannot control the spa with the dashboard either.

https://community.hubitat.com/uploads/default/original/3X/6/4/644950d6661e6f86ce24c086f89f3c7922ea07d6.jpeg

The virtual buttons look weird to me too. There is no status or control over the virtual temperature, for example. I would expect to see something other than one button here, maybe a current status of temperature or a thermostat or something.

https://community.hubitat.com/uploads/default/optimized/3X/6/3/63c954ed32498cbff739595713bdf436ae299962_2_690x329.jpeg

It also broke all my rules where this app was involved.

I rolled back for now, and all the errors went away.

**Comment by richardpowellus** [comment]
I posted a reply on the Hubitat forum as well :) Here it is:

So the first issue I usually see whenever the App and drivers have become out of sync. That's almost guaranteed if you try and "upgrade" from the old app/driver to the new one. You will need to completely uninstall the old app and delete the old devices/driver before installing the new app and drivers. Trying to support upgrading from the old app/driver to the new one, while possible, will be quite a tedious process and I'm not sure it's worthwhile for the small number of us that will be using this app.

Can you try doing a clean install and then let me know if the issue is resolved?

As for the second issue, this is expected with the new parent/child model. You will now find all the controls for the current status, temperature, etc. with the new thermostat child device. Once you have installed the new app then go to the device list and you will see you have a new child device listed under your parent device that is a dedicated thermostat device. If you click on that thermostat device it will give you all the controls you're looking for.
